In [4]:
import numpy as np
import pandas as pd
import time
import plotly.express as px
import json

## Finding the LCS

In [13]:
np.random.seed(42)

class Sequence():
    def __init__(self, length, char):
        self.length = length
        self.char = char
        
    def generate_sequence(self):
        # generate a random sequence of size self.length with the self.char characters
        return np.random.choice(list(self.char), size=self.length)
        
        creates
        
def find_LCS(X, Y):
    return 
                
length_LCS =  []
seq_length = 10
char = ["a", "b"]
nb_char = len(np.unique(char))
X = Sequence(3, char).generate_sequence()
Y = Sequence(4, char).generate_sequence()
find_LCS(X, Y)

In [14]:
np.random.seed(24)
X = Sequence(6, char).generate_sequence()
Y = Sequence(5, char).generate_sequence()

# method starts here
m = len(X)
n = len(Y)
T = np.empty((m+1, n+1))
T[:] = 999

for i in range(m+1):
    for j in range(n+1):
        if i == 0 or j == 0:
            T[i][j] = 0
        elif X[i-1] == Y[j-1]:
            T[i][j] = T[i-1][j-1] + 1
        else:
            T[i][j] = np.maximum(T[i-1][j], T[i][j-1])
        display(pd.DataFrame(T, columns=np.concatenate([[999], Y]), index=np.concatenate([[999], X]), dtype=int))
        

T

999    b    a    b    b    a
999    0  999  999  999  999  999
a    999  999  999  999  999  999
b    999  999  999  999  999  999
a    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999

999    b    a    b    b    a
999    0    0  999  999  999  999
a    999  999  999  999  999  999
b    999  999  999  999  999  999
a    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999

999    b    a    b    b    a
999    0    0    0  999  999  999
a    999  999  999  999  999  999
b    999  999  999  999  999  999
a    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999

999    b    a    b    b    a
999    0    0    0    0  999  999
a    999  999  999  999  999  999
b    999  999  999  999  999  999
a    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999

999    b    a    b    b    a
999    0    0    0    0    0  999
a    999  999  999  999  999  999
b    999  999  999  999  999  999
a    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999

999    b    a    b    b    a
999    0    0    0    0    0    0
a    999  999  999  999  999  999
b    999  999  999  999  999  999
a    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999

999    b    a    b    b    a
999    0    0    0    0    0    0
a      0  999  999  999  999  999
b    999  999  999  999  999  999
a    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999

999    b    a    b    b    a
999    0    0    0    0    0    0
a      0    0  999  999  999  999
b    999  999  999  999  999  999
a    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999

999    b    a    b    b    a
999    0    0    0    0    0    0
a      0    0    1  999  999  999
b    999  999  999  999  999  999
a    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999

999    b    a    b    b    a
999    0    0    0    0    0    0
a      0    0    1    1  999  999
b    999  999  999  999  999  999
a    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999

999    b    a    b    b    a
999    0    0    0    0    0    0
a      0    0    1    1    1  999
b    999  999  999  999  999  999
a    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999

999    b    a    b    b    a
999    0    0    0    0    0    0
a      0    0    1    1    1    1
b    999  999  999  999  999  999
a    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999

999    b    a    b    b    a
999    0    0    0    0    0    0
a      0    0    1    1    1    1
b      0  999  999  999  999  999
a    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999

999    b    a    b    b    a
999    0    0    0    0    0    0
a      0    0    1    1    1    1
b      0    1  999  999  999  999
a    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999

999    b    a    b    b    a
999    0    0    0    0    0    0
a      0    0    1    1    1    1
b      0    1    1  999  999  999
a    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999

999    b    a    b    b    a
999    0    0    0    0    0    0
a      0    0    1    1    1    1
b      0    1    1    2  999  999
a    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999

999    b    a    b    b    a
999    0    0    0    0    0    0
a      0    0    1    1    1    1
b      0    1    1    2    2  999
a    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999

999    b    a    b    b    a
999    0    0    0    0    0    0
a      0    0    1    1    1    1
b      0    1    1    2    2    2
a    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999

999    b    a    b    b    a
999    0    0    0    0    0    0
a      0    0    1    1    1    1
b      0    1    1    2    2    2
a      0  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999

999    b    a    b    b    a
999    0    0    0    0    0    0
a      0    0    1    1    1    1
b      0    1    1    2    2    2
a      0    1  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999

999    b    a    b    b    a
999    0    0    0    0    0    0
a      0    0    1    1    1    1
b      0    1    1    2    2    2
a      0    1    2  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999

999    b    a    b    b    a
999    0    0    0    0    0    0
a      0    0    1    1    1    1
b      0    1    1    2    2    2
a      0    1    2    2  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999

999    b    a    b    b    a
999    0    0    0    0    0    0
a      0    0    1    1    1    1
b      0    1    1    2    2    2
a      0    1    2    2    2  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999

999    b    a    b    b    a
999    0    0    0    0    0    0
a      0    0    1    1    1    1
b      0    1    1    2    2    2
a      0    1    2    2    2    3
b    999  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999

999    b    a    b    b    a
999    0    0    0    0    0    0
a      0    0    1    1    1    1
b      0    1    1    2    2    2
a      0    1    2    2    2    3
b      0  999  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999

999    b    a    b    b    a
999    0    0    0    0    0    0
a      0    0    1    1    1    1
b      0    1    1    2    2    2
a      0    1    2    2    2    3
b      0    1  999  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999

999    b    a    b    b    a
999    0    0    0    0    0    0
a      0    0    1    1    1    1
b      0    1    1    2    2    2
a      0    1    2    2    2    3
b      0    1    2  999  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999

999    b    a    b    b    a
999    0    0    0    0    0    0
a      0    0    1    1    1    1
b      0    1    1    2    2    2
a      0    1    2    2    2    3
b      0    1    2    3  999  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999

999    b    a    b    b    a
999    0    0    0    0    0    0
a      0    0    1    1    1    1
b      0    1    1    2    2    2
a      0    1    2    2    2    3
b      0    1    2    3    3  999
b    999  999  999  999  999  999
b    999  999  999  999  999  999

999    b    a    b    b    a
999    0    0    0    0    0    0
a      0    0    1    1    1    1
b      0    1    1    2    2    2
a      0    1    2    2    2    3
b      0    1    2    3    3    3
b    999  999  999  999  999  999
b    999  999  999  999  999  999

999    b    a    b    b    a
999    0    0    0    0    0    0
a      0    0    1    1    1    1
b      0    1    1    2    2    2
a      0    1    2    2    2    3
b      0    1    2    3    3    3
b      0  999  999  999  999  999
b    999  999  999  999  999  999

999    b    a    b    b    a
999    0    0    0    0    0    0
a      0    0    1    1    1    1
b      0    1    1    2    2    2
a      0    1    2    2    2    3
b      0    1    2    3    3    3
b      0    1  999  999  999  999
b    999  999  999  999  999  999

999    b    a    b    b    a
999    0    0    0    0    0    0
a      0    0    1    1    1    1
b      0    1    1    2    2    2
a      0    1    2    2    2    3
b      0    1    2    3    3    3
b      0    1    2  999  999  999
b    999  999  999  999  999  999

999    b    a    b    b    a
999    0    0    0    0    0    0
a      0    0    1    1    1    1
b      0    1    1    2    2    2
a      0    1    2    2    2    3
b      0    1    2    3    3    3
b      0    1    2    3  999  999
b    999  999  999  999  999  999

999    b    a    b    b    a
999    0    0    0    0    0    0
a      0    0    1    1    1    1
b      0    1    1    2    2    2
a      0    1    2    2    2    3
b      0    1    2    3    3    3
b      0    1    2    3    4  999
b    999  999  999  999  999  999

999    b    a    b    b    a
999    0    0    0    0    0    0
a      0    0    1    1    1    1
b      0    1    1    2    2    2
a      0    1    2    2    2    3
b      0    1    2    3    3    3
b      0    1    2    3    4    4
b    999  999  999  999  999  999

999    b    a    b    b    a
999    0    0    0    0    0    0
a      0    0    1    1    1    1
b      0    1    1    2    2    2
a      0    1    2    2    2    3
b      0    1    2    3    3    3
b      0    1    2    3    4    4
b      0  999  999  999  999  999

999  b    a    b    b    a
999    0  0    0    0    0    0
a      0  0    1    1    1    1
b      0  1    1    2    2    2
a      0  1    2    2    2    3
b      0  1    2    3    3    3
b      0  1    2    3    4    4
b      0  1  999  999  999  999

999  b  a    b    b    a
999    0  0  0    0    0    0
a      0  0  1    1    1    1
b      0  1  1    2    2    2
a      0  1  2    2    2    3
b      0  1  2    3    3    3
b      0  1  2    3    4    4
b      0  1  2  999  999  999

999  b  a  b    b    a
999    0  0  0  0    0    0
a      0  0  1  1    1    1
b      0  1  1  2    2    2
a      0  1  2  2    2    3
b      0  1  2  3    3    3
b      0  1  2  3    4    4
b      0  1  2  3  999  999

999  b  a  b  b    a
999    0  0  0  0  0    0
a      0  0  1  1  1    1
b      0  1  1  2  2    2
a      0  1  2  2  2    3
b      0  1  2  3  3    3
b      0  1  2  3  4    4
b      0  1  2  3  4  999

999  b  a  b  b  a
999    0  0  0  0  0  0
a      0  0  1  1  1  1
b      0  1  1  2  2  2
a      0  1  2  2  2  3
b      0  1  2  3  3  3
b      0  1  2  3  4  4
b      0  1  2  3  4  4

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1.],
       [0., 1., 1., 2., 2., 2.],
       [0., 1., 2., 2., 2., 3.],
       [0., 1., 2., 3., 3., 3.],
       [0., 1., 2., 3., 4., 4.],
       [0., 1., 2., 3., 4., 4.]])

In [58]:
np.concatenate([[999], Y])

array([999,   0,   1,   0,   0,   0])

In [53]:
T

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1.],
       [0., 1., 2., 2., 2., 2.],
       [0., 1., 2., 3., 3., 3.],
       [0., 1., 2., 3., 4., 4.]])

# Save data to json

In [ ]:
time_start = time.time()    
for _ in range(200):
    my_sequence = Sequence(seq_length, char)
    seq1 = my_sequence.generate_sequence()
    seq2 = my_sequence.generate_sequence()

    length_LCS.append(find_LCS(seq1, seq2))

time_end = time.time()    
print(f"Time taken: {round(time_end - time_start, 2)}s")


lcs_data = {
        "nb characters": nb_char,
        "sequence length": seq_length,
        "length LCS": length_LCS,
}


def add_data():
    # read from json
    with open("lcs_data.json", "r") as f:
        data = json.load(f)
    # check if this type of sequence already exists in json file
    for item in data:
        if item["nb characters"] == lcs_data["nb characters"] and item["sequence length"] == lcs_data["sequence length"]:
            item["length LCS"] += length_LCS
            return data
    data.append(lcs_data)
    return data

data = add_data()

# write data to json file
with open("lcs_data.json", "w") as f:
    json.dump(data, f, indent=4)
        
# data

In [ ]:
existing_data

In [ ]:
[10, 12] + [10, 12]

# Visualisation

In [ ]:
px.histogram(lengths, nbins=25)