In [3]:
using Pkg
using StatsBase
using Random
using DataFrames

In [30]:
# Random.seed!(42)
mutable struct Sequence
    len::Int
    char::Array{Any}
end
function generate_sequence(seq::Sequence)
    sample(seq.char, seq.len)
end

function lcs_table(X, Y)
    # make table
    m = length(X)
    n = length(Y)
    T = zeros(Int, m+1, n+1)
    T[:] .= 999
    for i in 1:m+1
        for j in 1:n+1
            if i == 1 || j == 1
               T[i, j] = 0
            elseif X[i-1] == Y[j-1]
                T[i, j] = T[i-1, j-1] + 1
            else
                T[i, j] = maximum([T[i-1, j], T[i, j-1]])
            end
        end
    end
    return T
end

function lcs_from_table(T)
    m = size(T)[1]
    n = size(T)[2]

    index = T[m, n]
    lcs = Any[]

    i, j = m, n
    while i > 1 && j > 1
            if X[i-1] == Y[j-1]
                prepend!(lcs, [X[i-1]])
                j -= 1
                i -= 1
            elseif T[i-1, j] > T[i, j-1]
                i -= 1
            else
                j -= 1
            end
        end
    return lcs
end
# len = 100
# char = [0, 1, 2, 3, 4, 5]

# X = generate_sequence(Sequence(len, char))
# Y = generate_sequence(Sequence(42, char))
# println("  X: ", X)
# println("  Y: ", Y)
# T = lcs_table(X, Y)
# display(T)
# lcs = println(lcs_from_table(T))

101×43 Matrix{Int64}:
 0  0  0  0  0  0  0  0  0  0   0   0  …   0   0   0   0   0   0   0   0   0
 0  1  1  1  1  1  1  1  1  1   1   1      1   1   1   1   1   1   1   1   1
 0  1  1  1  2  2  2  2  2  2   2   2      2   2   2   2   2   2   2   2   2
 0  1  1  1  2  2  2  3  3  3   3   3      3   3   3   3   3   3   3   3   3
 0  1  1  1  2  2  2  3  4  4   4   4      4   4   4   4   4   4   4   4   4
 0  1  2  2  2  2  3  3  4  4   4   4  …   5   5   5   5   5   5   5   5   5
 0  1  2  2  2  2  3  3  4  4   4   4      6   6   6   6   6   6   6   6   6
 0  1  2  2  2  2  3  3  4  4   4   5      7   7   7   7   7   7   7   7   7
 0  1  2  2  2  2  3  3  4  4   4   5      8   8   8   8   8   8   8   8   8
 0  1  2  2  2  2  3  3  4  4   4   5      9   9   9   9   9   9   9   9   9
 0  1  2  3  3  3  3  3  4  5   5   5  …  10  10  10  10  10  10  10  10  10
 0  1  2  3  3  3  3  3  4  5   5   5     11  11  11  11  11  11  11  11  11
 0  1  2  3  3  3  3  3  4  5   5   6     12  12  12  

  X: Any[4, 1, 1, 4, 5, 5, 4, 5, 3, 2, 3, 4, 3, 1, 5, 3, 0, 5, 4, 5, 2, 0, 0, 3, 4, 3, 2, 3, 5, 0, 2, 1, 0, 2, 1, 2, 0, 0, 5, 5, 4, 1, 0, 5, 4, 4, 3, 2, 1, 3, 3, 0, 5, 4, 1, 5, 1, 5, 5, 0, 0, 4, 3, 1, 0, 2, 1, 1, 0, 0, 3, 3, 4, 2, 1, 5, 5, 1, 0, 5, 5, 1, 0, 1, 5, 2, 2, 4, 5, 1, 1, 0, 1, 2, 0, 5, 2, 1, 4, 3]
  Y: Any[4, 5, 2, 1, 2, 5, 1, 4, 2, 2, 4, 2, 1, 0, 0, 5, 1, 5, 0, 4, 5, 1, 3, 3, 2, 1, 3, 0, 1, 1, 5, 5, 4, 5, 0, 3, 0, 2, 3, 1, 5, 0]
Any[4, 5, 2, 1, 2, 5, 1, 2, 2, 4, 2, 1, 0, 5, 1, 5, 0, 4, 1, 3, 3, 2, 1, 0, 1, 1, 5, 4, 5, 0, 0, 2, 3]


In [41]:
# find length of lcs depending on

len = 10
char = [0, 1]
X = generate_sequence(Sequence(len, char))
Y = generate_sequence(Sequence(len, char))
println("  X: ", X)
println("  Y: ", Y)
T = lcs_table(X, Y)
display(T)
lcs = println(lcs_from_table(T))

11×11 Matrix{Int64}:
 0  0  0  0  0  0  0  0  0  0  0
 0  0  1  1  1  1  1  1  1  1  1
 0  1  1  1  1  2  2  2  2  2  2
 0  1  2  2  2  2  2  2  3  3  3
 0  1  2  3  3  3  3  3  3  3  3
 0  1  2  3  4  4  4  4  4  4  4
 0  1  2  3  4  5  5  5  5  5  5
 0  1  2  3  4  5  6  6  6  6  6
 0  1  2  3  4  5  6  6  7  7  7
 0  1  2  3  4  5  6  7  7  8  8
 0  1  2  3  4  5  6  7  8  8  8

  X: Any[1, 0, 1, 1, 1, 0, 0, 1, 0, 1]
  Y: Any[0, 1, 1, 1, 0, 0, 0, 1, 0, 0]
Any[0, 1, 1, 1, 0, 0, 0, 1]


3-element Vector{Any}:
 4
 1
 3